#include "chopper/Exporters.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>

namespace chopper {
namespace {

void putVarLen(std::vector<uint8_t>& b, uint32_t v)
{
    uint8_t buf[5]; int n = 0;
    do { buf[n++] = uint8_t(v & 0x7F); v >>= 7; } while (v);
    while (n--) b.push_back(uint8_t(buf[n] | (n ? 0x80 : 0)));
}
void putBE32(std::vector<uint8_t>& b, uint32_t v) { b.push_back(uint8_t(v >> 24)); b.push_back(uint8_t(v >> 16)); b.push_back(uint8_t(v >> 8)); b.push_back(uint8_t(v)); }
void putBE16(std::vector<uint8_t>& b, uint16_t v) { b.push_back(uint8_t(v >> 8)); b.push_back(uint8_t(v)); }

bool writeBytes(const std::string& path, const std::vector<uint8_t>& bytes, std::string& error)
{
    std::ofstream f(path, std::ios::binary);
    if (!f) { error = "cannot open for writing: " + path; return false; }
    f.write(reinterpret_cast<const char*>(bytes.data()), std::streamsize(bytes.size()));
    if (!f) { error = "write failed: " + path; return false; }
    return true;
}
bool writeText(const std::string& path, const std::string& text, std::string& error)
{
    std::ofstream f(path, std::ios::binary);
    if (!f) { error = "cannot open for writing: " + path; return false; }
    f << text;
    if (!f) { error = "write failed: " + path; return false; }
    return true;
}
std::string jsonEscape(const std::string& s)
{
    std::string o; for (char c : s) { if (c == '"' || c == '\\') { o += '\\'; o += c; } else if ((unsigned char)c < 32) o += ' '; else o += c; } return o;
}
std::string fmt(double v, int decimals)
{
    std::ostringstream ss; ss.setf(std::ios::fixed); ss.precision(decimals); ss << v; return ss.str();
}

} // namespace

bool writeSliceMidi(const std::string& path, const std::vector<ExportedSlice>& slices,
                    double bpm, int velocity, std::string& error)
{
    if (bpm <= 0) bpm = 120.0;
    const uint32_t ppq = 960;
    const double ticksPerSecond = bpm / 60.0 * ppq;
    struct Ev { uint32_t tick; int order; std::vector<uint8_t> bytes; };
    std::vector<Ev> evs;
    for (const auto& s : slices) {
        const uint32_t on  = uint32_t(std::llround(s.startSeconds * ticksPerSecond));
        uint32_t off = uint32_t(std::llround((s.startSeconds + s.lengthSeconds) * ticksPerSecond));
        if (off <= on) off = on + 1;
        const uint8_t note = uint8_t(std::clamp(s.midiNote, 0, 127)), vel = uint8_t(std::clamp(velocity, 1, 127));
        evs.push_back({ off, 0, { 0x80, note, 0 } });     // note-offs first at equal ticks
        evs.push_back({ on,  1, { 0x90, note, vel } });
    }
    std::stable_sort(evs.begin(), evs.end(), [](const Ev& a, const Ev& b) { return a.tick != b.tick ? a.tick < b.tick : a.order < b.order; });

    std::vector<uint8_t> track;
    // tempo + time signature + track name
    putVarLen(track, 0); track.insert(track.end(), { 0xFF, 0x51, 0x03 });
    const uint32_t usPerQuarter = uint32_t(std::llround(60000000.0 / bpm));
    track.push_back(uint8_t(usPerQuarter >> 16)); track.push_back(uint8_t(usPerQuarter >> 8)); track.push_back(uint8_t(usPerQuarter));
    putVarLen(track, 0); track.insert(track.end(), { 0xFF, 0x58, 0x04, 0x04, 0x02, 0x18, 0x08 });
    const std::string name = "Slices";
    putVarLen(track, 0); track.insert(track.end(), { 0xFF, 0x03 }); putVarLen(track, uint32_t(name.size())); track.insert(track.end(), name.begin(), name.end());
    uint32_t last = 0;
    for (const auto& e : evs) { putVarLen(track, e.tick - last); last = e.tick; track.insert(track.end(), e.bytes.begin(), e.bytes.end()); }
    putVarLen(track, 0); track.insert(track.end(), { 0xFF, 0x2F, 0x00 });

    std::vector<uint8_t> out;
    out.insert(out.end(), { 'M', 'T', 'h', 'd' }); putBE32(out, 6); putBE16(out, 0); putBE16(out, 1); putBE16(out, uint16_t(ppq));
    out.insert(out.end(), { 'M', 'T', 'r', 'k' }); putBE32(out, uint32_t(track.size())); out.insert(out.end(), track.begin(), track.end());
    return writeBytes(path, out, error);
}

bool writeSfz(const std::string& path, const std::vector<ExportedSlice>& slices,
              const std::string& instrumentName, std::string& error)
{
    std::ostringstream s;
    s << "// " << instrumentName << " - generated by Sample Chopper\n"
      << "// One slice per key, one-shot. Drop the .sfz and the .wav files in the same folder.\n\n"
      << "<control>\ndefault_path=\n\n"
      << "<global>\nloop_mode=one_shot\nampeg_release=0.05\n\n"
      << "<group>\n";
    for (const auto& sl : slices)
        s << "<region> sample=" << sl.fileName << " key=" << sl.midiNote << "\n";
    return writeText(path, s.str(), error);
}

bool writeJsonManifest(const std::string& path, const std::string& sourceName, double sampleRate,
                       double bpm, int rootNote, const std::vector<ExportedSlice>& slices, std::string& error)
{
    std::ostringstream j;
    j << "{\n  \"generator\": \"Sample Chopper\",\n"
      << "  \"source\": \"" << jsonEscape(sourceName) << "\",\n"
      << "  \"sampleRate\": " << fmt(sampleRate, 0) << ",\n"
      << "  \"bpm\": " << fmt(bpm, 3) << ",\n"
      << "  \"rootNote\": " << rootNote << ",\n"
      << "  \"slices\": [\n";
    for (size_t i = 0; i < slices.size(); ++i) {
        const auto& s = slices[i];
        j << "    {\"index\": " << (i + 1) << ", \"file\": \"" << jsonEscape(s.fileName) << "\", \"midiNote\": " << s.midiNote
          << ", \"startSample\": " << s.start << ", \"endSample\": " << s.end
          << ", \"startSeconds\": " << fmt(s.startSeconds, 6) << ", \"lengthSeconds\": " << fmt(s.lengthSeconds, 6) << "}"
          << (i + 1 < slices.size() ? ",\n" : "\n");
    }
    j << "  ]\n}\n";
    return writeText(path, j.str(), error);
}

bool writeMarkerWav(const std::string& path, const AudioData& source, const std::vector<Slice>& slices,
                    const std::vector<std::string>& labels, BitDepth depth, std::string& error)
{
    WavWriteOptions o; o.bitDepth = depth;
    for (size_t i = 0; i < slices.size(); ++i) {
        WavMarker m; m.sampleOffset = uint32_t(slices[i].start);
        m.label = i < labels.size() ? labels[i] : "Slice " + std::to_string(i + 1);
        o.markers.push_back(m);
    }
    return writeWav(path, source, o, error);
}

} // namespace chopper
